### PR TITLE
Improve examples

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes https://github.com/vaadin/vaadin-app-layout-flow/issues/118

Show code examples on the page. Due to https://github.com/vaadin/vaadin-app-layout-flow/issues/125 should be embedded and shown via iframe

---
This is the same as #123 but not from a fork, to run build on SauceLabs.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-app-layout-flow/129)

### CODE REVIEW

**Comment by anasmi** [comment]
@alvarezguille I've run them locally only, so no integration testing with a Vaadin com side were run. Could you say how this should be done? I am willing to verify I haven't broke anything :)

**Comment by alvarezguille** [comment]
@anasmi you'd need to run vaadin.com project locally and override the project version of `vaadin-app-layout-flow-demo` artifact with a locally built snapshot with the changes of this PR.

I haven't tested myself but I fear it won't work, for this to work `vaadin.com/applayoutdrawermenu` should be available

One possible alternative to this approach is the one mentioned in this comment https://github.com/vaadin/vaadin-app-layout-flow/issues/118#issuecomment-557434597

**Comment by anasmi** [comment]
Run locally on vaadin.com. Indeed this doesn't work as expected....

**Comment by anasmi** [comment]
This pull request is replaced by this one https://github.com/vaadin/vaadin-app-layout-flow/pull/137

**Comment by alvarezguille** [comment]
Closing as inactive. If this is still needed, please re-apply to https://github.com/vaadin/vaadin-flow-components

**Pull request closed without merging**
